spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liLIkyk1RK0wxR8y
            client-secret: a30cd9b6aed775a1d76fc29ce2fdf9556cc67fa3
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/oms/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

#    # fix redirect after login
#    default-success-url: /home  # or any public, non-secured page