spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: order-service-user
    password: order-service-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true