server:
  port: 8080
  forward-headers-strategy: framework  # If behind proxy
  servlet:
    session:
      cookie:
        same-site: lax     # Avoid SameSite issues
        secure: false      # Only true if using HTTPS

spring:
  thymeleaf:
    cache: false        # Disable caching for development
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liLIkyk1RK0wxR8y
            client-secret: a30cd9b6aed775a1d76fc29ce2fdf9556cc67fa3
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
