server:
  port: 8080
  forward-headers-strategy: framework  # If behind proxy
  servlet:
    session:
      cookie:
        same-site: lax     # Avoid SameSite issues
        secure: false      # Only true if using HTTPS

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
