spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_order_db
    username: test-order-service-user
    password: test-order-service-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true